### ISSUE TITLE
大佬公众号什么时候恢复

### ISSUE THREAD

**Issue by liudongv2** [polyrabbit/WeCron#10]
大佬公众号什么时候恢复

**Comment by zshy1205** [comment]
@liudongv2 有找到相关替代软件吗。。

**Comment by yutianqi** [comment]
期待恢复

**Comment by polyrabbit** [comment]
![Lark20210118-211903](https://user-images.githubusercontent.com/2657334/104920494-d4047c00-59d2-11eb-838e-5e93a35cd95b.gif)

已经申请到银行的对公账户了。。。

**Comment by backwind1233** [comment]
大佬，求恢复

**Comment by polyrabbit** [comment]
@liudongv2 @zshy1205 @yutianqi 已经恢复八成血了，想要试用请参考 https://github.com/polyrabbit/WeCron/issues/11#issuecomment-837879418

**Comment by zshy1205** [comment]
> @liudongv2 @zshy1205 @yutianqi 已经恢复八成血了，想要试用请参考 [#11 (comment)](https://github.com/polyrabbit/WeCron/issues/11#issuecomment-837879418)

好滴，感谢大佬
