### ISSUE TITLE
您好，请问服务什么时候能恢复呢？

### ISSUE THREAD

**Issue by yutianqi** [polyrabbit/WeCron#11]
您好，首先非常感谢您为社区提供了这么一款实用、好用又免费的服务。谢谢您。
但这个服务从前段时间开始似乎就不可用了，请问有恢复的计划吗？
如果不再继续开放的话，请问之前的那些提醒有什么办法可以导出来吗？

**Comment by polyrabbit** [comment]
会开放的，如果不放心，可以先加我的微信，我把你之前的提醒都导给你，具体联系方式，从公众号里应该不难找

**Comment by yutianqi** [comment]
真的没有找到...我的微信号是 Duke98842674 ，能否劳烦您加一下我，非常感谢。

**Comment by linruiand** [comment]
同重度用户，期待早日开通

**Comment by backwind1233** [comment]
重度用户  希望早日开放

**Comment by uptownboy** [comment]
大佬，这个小程序还会恢复吗？这么好用，不要没了啊

**Comment by JD-Wang** [comment]
参考[server酱](http://sc.ftqq.com/)可以接企业微信、钉钉小程序、bark等其他渠道提醒啊
重度用户，再不行我就要自建服务了

**Comment by gary02** [comment]
现在5-11, 微定时已经能用了， 不过换了个号，叫“微定时 WeCron"

**Comment by polyrabbit** [comment]
@yutianqi @linruiand @backwind1233 @uptownboy @JD-Wang @gary02 
可能大家有人已经发现了，由于绑定公司主体过期的问题，我把现有的功能都迁移到新号`微定时WeCron`，欢迎大家扫码关注，继续使用。目前还没有发公告是因为历史记录的关联还有些问题，不过这不影响新提醒的使用。

![扫码_微定时WeCron](https://user-images.githubusercontent.com/2657334/117764620-64571d00-b25f-11eb-857a-d8c12932065f.png)

**Comment by backwind1233** [comment]
@polyrabbit  谢谢
