### ISSUE TITLE
你好，请问下 模版消息是使用哪个行业的？

### ISSUE THREAD

**Issue by try3** [polyrabbit/WeCron#3]
在微信提供的模版库中为什么搜索不到这个模版消息呢？
能请问下，这个模版消息是在哪个行业下面的吗？

**Comment by polyrabbit** [comment]
Hi，我用的是**IT软件与服务**下面的待办任务提醒模板：
![image](https://user-images.githubusercontent.com/2657334/28580652-bee7ad3c-7192-11e7-9696-ec64d7dbcf49.png)
