### ISSUE TITLE
能加个每小时或者半小时提醒吗？ 比如半小时动一动 

### ISSUE THREAD

**Issue by 24** [polyrabbit/WeCron#4]
RT

**Comment by polyrabbit** [comment]
实现上面没问题，但频率太高很可能对用户造成骚扰的感觉，也容易被微信封禁啊。

**Comment by 24** [comment]
如果用户选择 半小时通知 或者隔天，每天 通知，都是用户自己选择， 频率高低是用户选择的
封倒是不会吧，因为这是用户自己的要求。我记得以前我们服务号是15分钟提醒，也没事的(不打保票！)。
可以试试  :)

**Comment by renzhuang** [comment]
能不能添加一个在我没没看到的一段时间内持续给我发通知的功能。例如三分钟内没看到发一次，超过半个小时没看见就不管了

**Comment by polyrabbit** [comment]
能不能推荐一个简洁的方法，让微定时知道用户3分钟内有没有看到通知？据我所知，微信是没有查看用户是否阅读消息的API的。

**Comment by renzhuang** [comment]
如果没有这个api的话，到提醒的时间点的时候让用户主动回复消息给公众号(回复文字  或者  点击button)，公众号收到后就停止向这个用户发送通知。

**Comment by uigdwunm** [comment]
我就想找一个评论题目要求的功能，找到了这个，但是很可惜还不能实现。感觉大部分人在微信上找定时提醒都是来找这个功能的吧，毕竟长期的提醒基本各种手机都有内置的功能。但这种短时的、打扰程度轻的，半小时提醒一次，非常适合长期在电脑前办公的人。希望能推出这个功能
