### ISSUE TITLE
请教一下Django的问题

### ISSUE THREAD

**Issue by zanderzhg** [polyrabbit/WeCron#5]
您好。打扰您了
我刚开始学习Django。
通过您的这个项目。一点一点的消化。我学到了很多。扩展user。View的dispatch。等等等等
我想请教您2个问题

1.在自定义认证中

`def make_guest(**kw):
    u = UserModel(**kw)
    u.subscribe = False
    u.save = lambda **kw: 1
    return u`

请问lambda **kw : 1 是什么意思呀。我网上查lambda的用法。。也没看到这样写的

2.在扩展user中。最后一句有

`# A hack around django's not allowing override a parent model's attribute
WechatUser._meta.get_field('password').null = True`

绕过django，不允许重写父模型的属性。。没有理解这句

虽然这两个问题和您的项目没关系。但是您能给我讲一下么？

**Comment by polyrabbit** [comment]
Hi,

`lambda **kw: 1` 是指创建一个`lambda`方法，这个方法接受`**kwargs`这种命名参数，返回值永远是`1`，然后再把这个空方法赋值给`u.save`这个属性。我这样做是因为`authenticate`这个方法期望返回一个`user`对象，然后调用`user.save()`方法将这个用户存到数据库里，为了防止他将我虚拟出来的`user`也存到数据库里，我覆盖了真正`user`的`save`方法，使它永远返回成功，但是实际上却什么都没做。

`WechatUser._meta.get_field('password').null = True`
主要是WeCron的用户都是通过微信认证，而不是通过用户名密码认证，所以Django默认提供的`password`这个field就没有作用，但是Django的`password`默认是必须要有的，否则它的`validator`会通不过，这里通过将`password`的`nullable`设为`True`告诉`validator`，这个`password`属性可以为空。

**Comment by zanderzhg** [comment]
收到.谢谢您.

**Comment by zanderzhg** [comment]
看了您的代码...惊喜不断...每个settings models views 里面都有收获

原来Django还可以这样写呀..真的感谢您能开源这个项目
