### ISSUE TITLE
自建公众号使用的话，需要在公众平台模板消息新建模板，替换模板ID

### ISSUE THREAD

**Issue by lvtu0316** [polyrabbit/WeCron#8]
这里当用户设置周期提醒的时候，如果用户没有与公众号互动，就会调用模板消息，所以需要使用有效的模板ID
新建模板的时候，我遇到的问题：
```
1、标题为“定时提醒”的模板消息审核不通过，原因是：并非用户触发事件后的通知。 补充说明：不支持此类模板消息，有骚扰用户倾向
2、标题为“提醒消息”的模板消息审核不通过，原因是：并非用户触发事件后的通知。 补充说明：模板消息是一个即时消息通知，是给用户提供服务后的服务凭证通知，不作提醒用途
```
不知道作者是怎么使用的模板消息。

**Comment by polyrabbit** [comment]
我用的是“待办任务提醒”，搜搜看能不能找到它：
![image](https://user-images.githubusercontent.com/2657334/91662578-faa24300-eb15-11ea-8a73-a064543dc8d0.png)

微信的审核确实比较迷，不仅仅是模板消息这一项，我不确信当时能用的模板现在还能不能用了
